# Generated by Django 5.2.x on 2026-01-04

from django.contrib.postgres.indexes import BTreeIndex
from django.db import migrations, models
import django.db.models.deletion


def set_existing_products_as_approved(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    # Existing catalog (no seller set) should be treated as approved.
    Product.objects.filter(seller__isnull=True).update(approval_status="approved")


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_sellersettlement_order_alter_userbadge_order"),
        ("product", "0202_category_product_category_tree_id_lf1e1"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Seller who owns/submitted this product (marketplace).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="marketplace.seller",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("requires_revision", "Requires Revision"),
                ],
                default="pending",
                help_text="Approval status for marketplace product workflow.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_exclusive_to_seller",
            field=models.BooleanField(
                default=False,
                help_text="Whether this product (and its SKUs) are exclusive to this seller.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Recommended retail price (baseline). Channel-level prior price may override.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="compliance_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Regulatory/compliance information (JSON).",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country_specific_pricing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-country pricing overrides (JSON).",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country_specific_stock",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-country inventory overrides (JSON).",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=BTreeIndex(fields=["approval_status"], name="product_approval_status_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=BTreeIndex(fields=["seller"], name="product_seller_idx"),
        ),
        migrations.RunPython(set_existing_products_as_approved, migrations.RunPython.noop),
    ]


