# Generated by Django 5.2.9 on 2025-12-30 08:36

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import saleor.core.utils.json_serializer
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
        ('channel', '0027_channel_allow_legacy_gift_card_use'),
        # ('order', '0220_orderline_seller'),  # Removed to avoid circular dependency - order FK will be added in separate migration
        # ('product', '0203_product_seller'),  # Removed to avoid circular dependency - product FK will be added in separate migration
        ('warehouse', '0035_alter_warehouse_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the badge', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the badge', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what the badge represents')),
                ('icon', models.ImageField(blank=True, help_text='Badge icon/image', null=True, upload_to='badge-icons')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this badge is currently active')),
                ('criteria_type', models.CharField(choices=[('order_count', 'Order Count'), ('total_spent', 'Total Spent'), ('loyalty_points', 'Loyalty Points'), ('manual', 'Manual Assignment')], help_text='Type of criteria for earning this badge', max_length=32)),
                ('criteria_value', models.IntegerField(blank=True, help_text='Value required to earn this badge (e.g., 10 orders, 1000 points)', null=True)),
                ('points_reward', models.IntegerField(default=0, help_text='Points awarded when this badge is earned', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('name',),
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['slug'], name='badge_slug_idx'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='badge_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='FandomCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Character name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the character', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Character description/bio')),
                ('image', models.ImageField(blank=True, help_text='Character image', null=True, upload_to='fandom-characters')),
                ('fandom_universe', models.CharField(blank=True, help_text="Universe/fandom this character belongs to (e.g., 'Star Wars', 'Marvel')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this character is currently active')),
                ('featured', models.BooleanField(default=False, help_text='Whether to feature this character')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='character_slug_idx'), models.Index(fields=['fandom_universe'], name='character_universe_idx'), models.Index(fields=['is_active', 'featured'], name='character_active_featured_idx')],
            },
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the category', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text="Icon name/class for the category (e.g., 'faq', 'shipping')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for nested categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.helpcategory')),
            ],
            options={
                'verbose_name_plural': 'Help categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this article was published', null=True)),
                ('title', models.CharField(help_text='Article title', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the article', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Article content (Markdown or HTML)')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt/summary of the article')),
                ('order', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this article has been viewed')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this article')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this article is currently active')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('author', models.ForeignKey(blank=True, help_text='User who created/updated this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='account.user')),
                ('category', models.ForeignKey(blank=True, help_text='Category this article belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='marketplace.helpcategory')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ContactSupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(help_text='Unique ticket number', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Ticket subject', max_length=255)),
                ('message', models.TextField(help_text='Ticket message/content')),
                ('email', models.EmailField(help_text='Email address for contact (required for guest tickets)', max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level of the ticket', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to='account.user')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Staff member who resolved this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_support_tickets', to='account.user')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this ticket (null for guest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='account.user')),
                ('category', models.ForeignKey(blank=True, help_text='Category this ticket belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='marketplace.helpcategory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointsBalance',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0, help_text='Current points balance', validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_earned', models.IntegerField(default=0, help_text='Total points ever earned (for tracking)', validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_spent', models.IntegerField(default=0, help_text='Total points ever spent (for tracking)', validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(help_text='User who owns this balance', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points_balance', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('points', models.IntegerField(help_text='Number of points (positive for earned, negative for spent)')),
                ('balance_after', models.IntegerField(help_text="User's balance after this transaction")),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('expired', 'Expired'), ('adjusted', 'Adjusted')], help_text='Type of transaction', max_length=32)),
                ('description', models.TextField(blank=True, help_text="Description of the transaction (e.g., 'Points from order #123')")),
                ('expires_at', models.DateTimeField(blank=True, help_text='When these points expire (if applicable)', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Order that triggered this transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_points_transactions', to='order.order')),
                ('user', models.ForeignKey(help_text='User who earned or spent the points', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points_transactions', to='account.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the subscription was confirmed (double opt-in)', null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the subscription (homepage, checkout, etc.)', max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to='account.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary character for this product')),
                ('character', models.ForeignKey(help_text='Character associated with this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.fandomcharacter')),
                ('product', models.ForeignKey(help_text='Product associated with this character', on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='product.product')),
            ],
            options={
                'ordering': ('-is_primary', 'character__name'),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Quiz title', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the quiz', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Quiz description')),
                ('questions', models.JSONField(default=dict, help_text='JSON structure containing quiz questions and answers')),
                ('points_reward', models.IntegerField(default=0, help_text='Loyalty points awarded for completing this quiz')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quiz is currently active')),
                ('featured', models.BooleanField(default=False, help_text='Whether to feature this quiz')),
                ('character', models.ForeignKey(blank=True, help_text='Character this quiz is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='marketplace.fandomcharacter')),
                ('collection', models.ForeignKey(blank=True, help_text='Collection this quiz is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='product.collection')),
            ],
            options={
                'ordering': ('-featured', 'title'),
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict, help_text="JSON structure containing user's answers")),
                ('score', models.IntegerField(blank=True, help_text='Score/percentage achieved (0-100)', null=True)),
                ('points_awarded', models.IntegerField(default=0, help_text='Loyalty points awarded for this quiz')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='When the quiz was completed')),
                ('quiz', models.ForeignKey(help_text='Quiz that was taken', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='marketplace.quiz')),
                ('user', models.ForeignKey(help_text='User who took the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='account.user')),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the reward', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the reward', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the reward')),
                ('points_required', models.IntegerField(help_text='Points required to redeem this reward', validators=[django.core.validators.MinValueValidator(1)])),
                ('reward_type', models.CharField(choices=[('discount', 'Discount Code'), ('product', 'Free Product'), ('voucher', 'Gift Voucher'), ('shipping', 'Free Shipping')], help_text='Type of reward', max_length=32)),
                ('reward_value', models.DecimalField(blank=True, decimal_places=3, help_text='Value of the reward (e.g., discount amount, voucher amount)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reward is currently available')),
                ('quantity_available', models.IntegerField(blank=True, help_text='Number of times this reward can be redeemed (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_redeemed', models.IntegerField(default=0, help_text='Number of times this reward has been redeemed', validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(blank=True, help_text='When this reward becomes available', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this reward expires', null=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product for free product rewards', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_products', to='product.product')),
            ],
            options={
                'ordering': ('points_required', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('points_spent', models.IntegerField(help_text='Points spent to redeem this reward')),
                ('redemption_code', models.CharField(help_text='Unique code for this redemption (e.g., discount code, voucher code)', max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this redemption has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the redemption was used', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this redemption expires (if applicable)', null=True)),
                ('reward', models.ForeignKey(help_text='Reward that was redeemed', on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='marketplace.reward')),
                ('user', models.ForeignKey(help_text='User who redeemed the reward', on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='account.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller-logos')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=32)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connect account ID for payouts', max_length=255, null=True)),
                ('channel', models.OneToOneField(blank=True, help_text="Dedicated channel for this seller's storefront", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='channel.channel')),
                ('owner', models.ForeignKey(help_text='Primary owner/admin of the seller account', on_delete=django.db.models.deletion.PROTECT, related_name='owned_sellers', to='account.user')),
                ('staff', models.ManyToManyField(blank=True, help_text='Additional staff members with seller access', related_name='seller_staff', to='account.user')),
                ('tax_origin_address', models.ForeignKey(blank=True, help_text='Default address used as tax origin for this seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
            ],
            options={
                'ordering': ('store_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SellerDomain',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(help_text='Custom domain (e.g., store.example.com or example.com)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid domain format', regex='^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$')])),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this seller (only one per seller)')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('active', 'Active'), ('failed', 'Verification Failed'), ('inactive', 'Inactive')], default='pending', max_length=32)),
                ('verification_token', models.CharField(blank=True, help_text='Token for domain verification', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_enabled', models.BooleanField(default=False, help_text='Whether SSL certificate is enabled for this domain')),
                ('ssl_certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(help_text='Seller who owns this domain', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='marketplace.seller')),
            ],
            options={
                'ordering': ('seller', '-is_primary', 'domain'),
            },
        ),
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order_total', models.DecimalField(decimal_places=3, help_text="Total order amount (gross) for this seller's items", max_digits=20)),
                ('platform_fee', models.DecimalField(decimal_places=3, help_text='Platform fee deducted from order total', max_digits=20)),
                ('seller_earnings', models.DecimalField(decimal_places=3, help_text='Amount seller receives (order_total - platform_fee)', max_digits=20)),
                ('currency', models.CharField(help_text='Currency code for this settlement', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='Stripe Connect transfer ID if payout was made via Stripe', max_length=255, null=True)),
                ('payout_reference', models.CharField(blank=True, help_text='Internal reference for the payout transaction', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this settlement')),
                ('order', models.ForeignKey(blank=True, help_text='Order this settlement is for (null for batch settlements)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_settlements', to='order.order', db_constraint=False)),
                ('seller', models.ForeignKey(help_text='Seller who receives this settlement', on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='marketplace.seller')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellerTaxRegistration',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_type', models.CharField(choices=[('vat', 'VAT'), ('gst', 'GST'), ('sales_tax', 'Sales Tax'), ('other', 'Other')], max_length=32)),
                ('registration_number', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_registrations', to='marketplace.seller')),
            ],
            options={
                'ordering': ('seller', 'country', 'registration_type'),
            },
        ),
        migrations.CreateModel(
            name='SellerWarehouse',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary fulfillment center for this seller')),
                ('priority', models.IntegerField(default=0, help_text='Priority for fulfillment (lower number = higher priority)')),
                ('seller', models.ForeignKey(help_text='Seller who has access to this warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='marketplace.seller')),
                ('warehouse', models.ForeignKey(help_text='Warehouse/fulfillment center', on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('seller', 'priority', 'warehouse'),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the HOS default theme')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this theme is available for use')),
                ('template_data', models.JSONField(default=dict, help_text='Theme template data (CSS variables, fonts, colors, etc.)')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme-previews')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['is_default'], name='theme_default_idx'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='theme_active_idx'), django.contrib.postgres.indexes.BTreeIndex(fields=['slug'], name='theme_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerStorefrontSettings',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_customizations', models.JSONField(default=dict, help_text='Customizations to the theme template (overrides template_data)')),
                ('primary_color', models.CharField(blank=True, default='#000000', help_text='Primary brand color (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Invalid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(blank=True, default='#FFFFFF', help_text='Secondary brand color (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Invalid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='seller-favicons')),
                ('storefront_logo', models.ImageField(blank=True, null=True, upload_to='seller-storefront-logos')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for storefront customization')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=255)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_settings', to='marketplace.seller')),
                ('theme', models.ForeignKey(blank=True, help_text="Active theme for this seller's storefront", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_settings', to='marketplace.theme')),
            ],
            options={
                'ordering': ('seller',),
            },
        ),
        migrations.CreateModel(
            name='ThemeVersion',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField()),
                ('template_data', models.JSONField(default=dict, help_text='Snapshot of template data at this version')),
                ('notes', models.TextField(blank=True, help_text='Release notes for this version')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marketplace.theme')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True, help_text='When the badge was earned')),
                ('badge', models.ForeignKey(help_text='Badge that was earned', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='marketplace.badge')),
                ('order', models.ForeignKey(blank=True, help_text='Order that triggered this badge (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_earned', to='order.order', db_constraint=False)),
                ('user', models.ForeignKey(help_text='User who earned the badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='account.user')),
            ],
            options={
                'ordering': ('-earned_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactSupportTicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField(help_text='Message content')),
                ('is_internal', models.BooleanField(default=False, help_text='Whether this is an internal note (not visible to customer)')),
                ('ticket', models.ForeignKey(help_text='Ticket this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.contactsupportticket')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent this message (null for system messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_messages', to='account.user')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['ticket'], name='support_ticket_msg_ticket_idx'), models.Index(fields=['created_at'], name='support_ticket_msg_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the viewer', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('article', models.ForeignKey(help_text='Article that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='marketplace.helparticle')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the article (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_article_views', to='account.user')),
            ],
            options={
                'ordering': ('-viewed_at',),
                'indexes': [models.Index(fields=['article'], name='help_article_view_article_idx'), models.Index(fields=['viewed_at'], name='help_article_view_date_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='helpcategory',
            index=models.Index(fields=['slug'], name='help_category_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='helpcategory',
            index=models.Index(fields=['parent', 'order'], name='help_category_parent_order_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['slug'], name='help_article_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['category', 'order'], name='help_article_cat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['is_active', 'is_featured'], name='help_article_active_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'content'], name='help_article_search_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contactsupportticket',
            index=models.Index(fields=['ticket_number'], name='support_ticket_number_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsupportticket',
            index=models.Index(fields=['status', 'priority'], name='support_ticket_stat_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsupportticket',
            index=models.Index(fields=['user'], name='support_ticket_user_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsupportticket',
            index=models.Index(fields=['assigned_to'], name='support_ticket_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointsbalance',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user'], name='loyalty_balance_user_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointsbalance',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['balance'], name='loyalty_balance_balance_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointstransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user'], name='loyalty_tx_user_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointstransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='loyalty_tx_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointstransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['transaction_type'], name='loyalty_tx_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['email'], name='newsletter_email_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='newsletter_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='newslettersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_newsletter_email'),
        ),
        migrations.AddIndex(
            model_name='productcharacter',
            index=models.Index(fields=['product'], name='product_char_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productcharacter',
            index=models.Index(fields=['character'], name='product_char_character_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcharacter',
            unique_together={('product', 'character')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['slug'], name='quiz_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', 'featured'], name='quiz_active_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['user'], name='quiz_submission_user_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['quiz'], name='quiz_submission_quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['completed_at'], name='quiz_submission_completed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('user', 'quiz')},
        ),
        migrations.AddIndex(
            model_name='reward',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['slug'], name='reward_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='reward_active_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['points_required'], name='reward_points_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user'], name='reward_redemption_user_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['reward'], name='reward_redemption_reward_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['redemption_code'], name='reward_redemption_code_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_used'], name='reward_redemption_used_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='seller_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='seller_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='seller_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['owner'], name='seller_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['slug'], name='seller_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.GinIndex(fields=['store_name', 'slug'], name='seller_search_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='sellerdomain',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='seller_domain_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdomain',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['domain'], name='seller_domain_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdomain',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='seller_domain_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdomain',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_primary'], name='seller_domain_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('seller', 'is_primary'), name='unique_primary_domain_per_seller'),
        ),
        migrations.AddIndex(
            model_name='sellersettlement',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='settlement_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersettlement',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='settlement_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersettlement',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='settlement_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersettlement',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['order'], name='settlement_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('seller', 'order'), name='unique_settlement_per_seller_order'),
        ),
        migrations.AddIndex(
            model_name='sellertaxregistration',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='seller_tax_reg_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellertaxregistration',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country'], name='seller_tax_reg_country_idx'),
        ),
        migrations.AddIndex(
            model_name='sellertaxregistration',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='seller_tax_reg_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellertaxregistration',
            constraint=models.UniqueConstraint(fields=('seller', 'registration_type', 'country', 'region'), name='unique_seller_tax_registration'),
        ),
        migrations.AddIndex(
            model_name='sellerwarehouse',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='seller_warehouse_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwarehouse',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['warehouse'], name='seller_warehouse_warehouse_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwarehouse',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_primary'], name='seller_warehouse_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerwarehouse',
            constraint=models.UniqueConstraint(fields=('seller', 'warehouse'), name='unique_seller_warehouse'),
        ),
        migrations.AddIndex(
            model_name='sellerstorefrontsettings',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['theme'], name='seller_settings_theme_idx'),
        ),
        migrations.AddIndex(
            model_name='themeversion',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['theme', 'version_number'], name='theme_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='themeversion',
            constraint=models.UniqueConstraint(fields=('theme', 'version_number'), name='unique_theme_version'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user'], name='user_badge_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['badge'], name='user_badge_badge_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['earned_at'], name='user_badge_earned_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
