# Generated by Django 5.2.9 on 2025-12-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('order', '0220_orderline_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersettlement',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this settlement is for (null for batch settlements)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_settlements', to='order.order'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order that triggered this badge (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_earned', to='order.order'),
        ),
    ]
