# Generated by Django 5.2.8 on 2025-12-30 14:48

import django.contrib.postgres.indexes
import django.db.models.deletion
import django_countries.fields
import saleor.core.utils.json_serializer
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
        ('channel', '0027_channel_allow_legacy_gift_card_use'),
        ('marketplace', '0002_alter_sellersettlement_order_alter_userbadge_order'),
        ('order', '0220_orderline_seller'),
        ('product', '0204_product_approval_status_product_compliance_data_and_more'),
        ('shipping', '0037_merge_20250630_1332'),
        ('warehouse', '0035_alter_warehouse_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentCenter',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the fulfillment center', max_length=255)),
                ('location', models.CharField(help_text="Location description (e.g., 'Liverpool, UK')", max_length=255)),
                ('country', django_countries.fields.CountryField(help_text='Country where the center is located', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fulfillment center is active')),
                ('priority', models.IntegerField(default=0, help_text='Priority for order routing (lower number = higher priority)')),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InventorySync',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_available', models.IntegerField(default=0, help_text='Available quantity at time of sync')),
                ('quantity_reserved', models.IntegerField(default=0, help_text='Reserved quantity at time of sync')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('sync_method', models.CharField(choices=[('webhook', 'Webhook'), ('polling', 'Polling'), ('manual', 'Manual')], default='polling', help_text='Method used for synchronization', max_length=32)),
            ],
            options={
                'ordering': ('-synced_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRoutingRule',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name/description of the routing rule', max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Priority for this rule (lower number = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this routing rule is active')),
                ('conditions', models.JSONField(default=dict, help_text='Routing conditions: inventory availability, delivery location, seller preference (JSON)')),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_name', models.CharField(help_text='Payment gateway name (Stripe, PayPal, etc.)', max_length=255)),
                ('gateway_config', models.JSONField(blank=True, default=dict, help_text='Gateway-specific configuration settings (JSON)')),
                ('enabled_countries', django_countries.fields.CountryField(blank=True, help_text='Countries where this gateway is enabled', max_length=752, multiple=True)),
                ('enabled_currencies', models.JSONField(blank=True, default=list, help_text='Currencies this gateway supports (JSON array)')),
                ('compliance_requirements', models.JSONField(blank=True, default=dict, help_text='Compliance requirements (PCI-DSS, etc.) (JSON)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gateway configuration is active')),
            ],
            options={
                'ordering': ('seller', 'gateway_name'),
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_type', models.CharField(choices=[('rrp', 'Recommended Retail Price'), ('cost_plus', 'Cost Plus'), ('promotional', 'Promotional'), ('seasonal', 'Seasonal')], help_text='Type of pricing rule', max_length=32)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (if applicable)', max_digits=5, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price override (if applicable)', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Start date for seasonal/promotional pricing', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='End date for seasonal/promotional pricing', null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country this pricing applies to (optional, for country-specific pricing)', max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing rule is active')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_revision', 'Requires Revision')], default='pending', max_length=32)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_period_days', models.PositiveIntegerField(help_text='Number of days within which returns are accepted')),
                ('return_conditions', models.JSONField(blank=True, default=dict, help_text='Return requirements and conditions (JSON)')),
                ('return_shipping_cost', models.CharField(choices=[('customer', 'Customer pays'), ('seller', 'Seller pays'), ('free', 'Free return shipping')], default='customer', help_text='Who pays for return shipping', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this return policy is active')),
            ],
            options={
                'ordering': ('seller', 'product', 'return_period_days'),
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(help_text='Reason for return')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='SellerLogisticsConfig',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfillment_method', models.CharField(choices=[('self_fulfill', 'Self Fulfill'), ('dropship', 'Dropship'), ('marketplace_fulfill', 'Marketplace Fulfill'), ('third_party', 'Third Party')], default='marketplace_fulfill', help_text='Method used for order fulfillment', max_length=32)),
                ('shipping_provider', models.CharField(blank=True, help_text='Shipping provider/carrier integration name', max_length=255, null=True)),
                ('handling_time_days', models.PositiveIntegerField(default=3, help_text='Number of days to handle/process orders (B2C: 1-3 days, B2B: 5-10 days)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order value threshold for free shipping (different for B2B vs B2C)', max_digits=10, null=True)),
                ('custom_shipping_methods', models.JSONField(blank=True, default=dict, help_text='Seller-specific shipping rates and methods (JSON)')),
                ('logistics_partner_integration', models.JSONField(blank=True, default=dict, help_text='Global logistics partner configuration (JSON)')),
            ],
            options={
                'ordering': ('seller',),
            },
        ),
        migrations.CreateModel(
            name='SellerShippingMethod',
            fields=[
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the shipping method', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Shipping price (base rate)', max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(blank=True, help_text='Estimated delivery time in days', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shipping method is active')),
                ('destination_country', django_countries.fields.CountryField(blank=True, help_text='Destination country for dynamic calculation (optional)', max_length=2, null=True)),
                ('destination_city', models.CharField(blank=True, help_text='Destination city for dynamic calculation (optional)', max_length=255, null=True)),
                ('tiered_pricing', models.JSONField(blank=True, default=dict, help_text='Tiered pricing rules by weight/price (JSON)')),
            ],
            options={
                'ordering': ('seller', 'name'),
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='Business registration number for B2B verification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='credit_terms_enabled',
            field=models.BooleanField(default=False, help_text='Whether credit terms (net 30, net 60, etc.) are enabled for B2B sellers'),
        ),
        migrations.AddField(
            model_name='seller',
            name='distributor_category',
            field=models.CharField(blank=True, choices=[('b2c_distributor', 'B2C Distributor (Single-piece retail)'), ('wholesale_distributor', 'Wholesale Distributor (Bulk sales only)')], help_text='Category for authorized distributors (B2C or Wholesale)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_authorized_distributor',
            field=models.BooleanField(default=False, help_text='Whether this seller is an authorized distributor'),
        ),
        migrations.AddField(
            model_name='seller',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum order quantity for B2B/wholesale sellers', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('b2b_wholesale', 'B2B Wholesale'), ('b2c_retail', 'B2C Retail'), ('hybrid', 'Hybrid (B2B & B2C)')], default='b2c_retail', help_text='Business model type: B2B Wholesale, B2C Retail, or Hybrid', max_length=32),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller_type'], name='seller_type_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_authorized_distributor'], name='seller_authorized_idx'),
        ),
        migrations.AddField(
            model_name='fulfillmentcenter',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Full address of the fulfillment center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AddField(
            model_name='fulfillmentcenter',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Saleor warehouses linked to this fulfillment center', related_name='fulfillment_centers', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorysync',
            name='fulfillment_center',
            field=models.ForeignKey(help_text='Fulfillment center this sync is for', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_syncs', to='marketplace.fulfillmentcenter'),
        ),
        migrations.AddField(
            model_name='inventorysync',
            name='product_variant',
            field=models.ForeignKey(help_text='Product variant being synced', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_syncs', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='inventorysync',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse being synced', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_syncs', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='orderroutingrule',
            name='fulfillment_center',
            field=models.ForeignKey(help_text='Fulfillment center this rule routes to', on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='marketplace.fulfillmentcenter'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller this gateway config applies to (optional, for seller-specific gateways)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_configs', to='marketplace.seller'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this rule applies to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='product.product'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller this rule applies to (for seller-wide rules)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='marketplace.seller'),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='product',
            field=models.ForeignKey(help_text='Product being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='product.product'),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_submissions_reviewed', to='account.user'),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='seller',
            field=models.ForeignKey(help_text='Seller who submitted this product', on_delete=django.db.models.deletion.CASCADE, related_name='product_submissions', to='marketplace.seller'),
        ),
        migrations.AddField(
            model_name='returnpolicy',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this policy applies to (optional, for SKU-specific policies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_policies', to='product.product'),
        ),
        migrations.AddField(
            model_name='returnpolicy',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller this policy applies to (optional, for seller-specific policies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_policies', to='marketplace.seller'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(help_text='Order this return is for', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='order.order'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_line',
            field=models.ForeignKey(help_text='Order line being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='order.orderline'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests_processed', to='account.user'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(help_text='Customer requesting the return', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='account.user'),
        ),
        migrations.AddField(
            model_name='sellerlogisticsconfig',
            name='primary_fulfillment_center',
            field=models.ForeignKey(blank=True, help_text='Primary fulfillment center for this seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='marketplace.fulfillmentcenter'),
        ),
        migrations.AddField(
            model_name='sellerlogisticsconfig',
            name='seller',
            field=models.OneToOneField(help_text='Seller this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logistics_config', to='marketplace.seller'),
        ),
        migrations.AddField(
            model_name='sellerlogisticsconfig',
            name='shipping_zones',
            field=models.ManyToManyField(blank=True, help_text='Shipping zones this seller can ship to', related_name='seller_logistics_configs', to='shipping.shippingzone'),
        ),
        migrations.AddField(
            model_name='sellershippingmethod',
            name='fulfillment_center',
            field=models.ForeignKey(blank=True, help_text='Fulfillment center this method applies to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_methods', to='marketplace.fulfillmentcenter'),
        ),
        migrations.AddField(
            model_name='sellershippingmethod',
            name='seller',
            field=models.ForeignKey(help_text='Seller who owns this shipping method', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='marketplace.seller'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentcenter',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country'], name='fulfillment_center_country_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentcenter',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='fulfillment_center_active_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentcenter',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['priority'], name='fulfillment_center_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysync',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['product_variant'], name='inventory_sync_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysync',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['fulfillment_center'], name='inventory_sync_center_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysync',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['synced_at'], name='inventory_sync_date_idx'),
        ),
        migrations.AddIndex(
            model_name='orderroutingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['fulfillment_center'], name='routing_rule_center_idx'),
        ),
        migrations.AddIndex(
            model_name='orderroutingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['priority'], name='routing_rule_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='orderroutingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='routing_rule_active_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='payment_gateway_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['gateway_name'], name='payment_gateway_name_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='payment_gateway_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['product'], name='pricing_rule_product_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='pricing_rule_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['pricing_type'], name='pricing_rule_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country'], name='pricing_rule_country_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='pricing_rule_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['valid_from'], name='pricing_rule_from_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['valid_until'], name='pricing_rule_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', True), ('seller__isnull', True), _negated=True), name='pricing_rule_requires_product_or_seller'),
        ),
        migrations.AddIndex(
            model_name='productsubmission',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='product_submission_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubmission',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='product_submission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubmission',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['submitted_at'], name='product_submission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpolicy',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='return_policy_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpolicy',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['product'], name='return_policy_product_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpolicy',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='return_policy_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', True), ('seller__isnull', True), _negated=True), name='return_policy_requires_seller_or_product'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['order'], name='return_request_order_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user'], name='return_request_user_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='return_request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['requested_at'], name='return_request_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerlogisticsconfig',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['fulfillment_method'], name='logistics_config_method_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerlogisticsconfig',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['primary_fulfillment_center'], name='logistics_config_center_idx'),
        ),
        migrations.AddIndex(
            model_name='sellershippingmethod',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['seller'], name='seller_shipping_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellershippingmethod',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='seller_shipping_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sellershippingmethod',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['destination_country'], name='seller_shipping_country_idx'),
        ),
    ]
