# Generated by Django 5.2.x on 2026-01-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_sellersettlement_order_alter_userbadge_order"),
        ("discount", "0087_merge_20250630_1332"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this voucher can only be applied to the seller's products.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="marketplace.seller",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this promotion applies only to products from this seller.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotions",
                to="marketplace.seller",
            ),
        ),
    ]


