# Generated by Django 5.2.x on 2026-01-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_sellersettlement_order_alter_userbadge_order"),
        ("order", "0216_merge_20250704_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Seller for this line (marketplace).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_lines",
                to="marketplace.seller",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="seller_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Denormalized seller name for this line (marketplace).",
                max_length=255,
            ),
        ),
    ]

# Generated manually for marketplace integration

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0219_merge_20251212_0955"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Seller who owns this order line (denormalized from product)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_lines",
                to="marketplace.seller",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="seller_name",
            field=models.CharField(
                blank=True,
                help_text="Denormalized seller store name for historical records",
                max_length=255,
                null=True,
            ),
        ),
    ]
